### ISSUE TITLE
dont know how or where to connect

### ISSUE THREAD

**Issue by HavoK979** [CakeLancelot/HeroesExtension#3]
I have no idea how or where to connect to the server using the game client.

**Comment by CakeLancelot** [comment]
The game is still Unity Web Player based, so you need a browser that supports plugins via NPAPI.

Here are instructions taken from the HeroesExtension Discord:
1. First, download a NPAPI capable web browser. The most accessible is the [Pale Moon](https://www.palemoon.org/download.shtml) browser. For Windows, make sure you are grabbing the 32-bit version.
2. Next, download and install Unity Web Player from [here](http://webplayer.unity3d.com/download_webplayer-3.x/UnityWebPlayer.exe).
3. Finally, open up Pale Moon (or whatever NPAPI browser you chose), and navigate to http://ffhclient.cakelancelot.net/ . The game should launch right away, you can change the displayed username using the text box in the upper left.

A guide for setting up servers locally is TBD.
